name: dhm_module_example_dev
channels:
  - conda-forge
dependencies:
  - python=3.7
  - click>=6.0
  - click-plugins>=1.0.0
  - black
  - pytest
  - pytest-clarity
  - pylint
  - pydocstyle
  - pip
  - gdal>=2.3
